plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.15.2"
defaults:
  # _posts
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true