plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.15.2"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
locale: "en-US"
title: "Data Focused Python"
name: "Brian J Kolowitz"
repository: "BrianKolowitz/data-focused-python"
logo: "/assets/images/logo_transparent_3.png"



theme: jekyll-theme-hacker