plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.15.2"
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
      values:
        sidebar:
          nav: "docs"
